<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>ToDo app</title>

	<!-- Tailwind -->
    <script src="https://cdn.tailwindcss.com"></script>

	<!-- Fonts -->

	<!-- Holtwood_One_SC -->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Holtwood+One+SC&display=swap" rel="stylesheet">

	<!-- Baloo_2 -->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Baloo+2:wght@400..800&display=swap" rel="stylesheet">

</head>
<body>
	<!-- Icons -->
	<?php include __DIR__ . '/../../../web/images/icons.svg'; ?>
	<?php echo $this->content(); ?>
</body>
</html>